### PR TITLE
Added encoder export to ONNX

### PR DESCRIPTION
**Pull request by visheratin**
Hi! Thank you so much for releasing such a powerful model. It is truly amazing!

I noticed that the ONNX export script didn't have encoder export, so I added it. The `export_decoder` method follows exactly the same logic as before. The `export_encoder` method is new, and it essentially exports the `Sam` image encoder. Plus, there is an additional flag for grouping external files into one file when the model is larger than 2 GB (only relevant for `vit_h`).

I also added the new notebook that runs both encoder and decoder in ONNX format. I didn't port image transformations to numpy because it looks like another task.

Implementation might be rough around the edges, please let me know if anything needs to be changed.

### CODE REVIEW

**Comment by danghung-Ptit** [comment]
Hi @visheratin , can you add the complete code for loading the encoder and decoder in ONNX format and making predictions, please?

**Comment by cainiaoshidai** [comment]
> The [notebook](https://github.com/visheratin/segment-anything/blob/main/notebooks/full_onnx_model_example.ipynb) from the PR has the complete code for using both the encoder and decoder for predictions. Let me know if something else needs to be added.

Hi,
Thank you so much for releasing the code of the export encoder to `onnx`.  When I inference the quantized `onnx` model using `onnxruntime` on the GPU, it is slower than the original `onnx` model. Can you give me some advice?
Thanks.
Best

**Comment by ericmintun** [comment]
I am glad this is proving useful to people, but our intent with the onnx code here was to give a minimal example of how we used onnx in the demo. We do not intend to provide full support for onnx export in the main codebase.

**Comment by cainiaoshidai** [comment]
> Since ONNX models are dynamically quantized, it adds some overheads to the inference. You can read more on that [here](https://onnxruntime.ai/docs/performance/model-optimizations/quantization.html#dynamic-quantization). Considering the diversity of use cases, I think that static quantization won't work well in the case of SAM. If you have a narrow use case, you can try to statically quantize the model using your target data as a [calibration dataset](https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/python/tools/quantization/calibrate.py).

Thanks. The dynamic quantization increases inference time by 80% on GPUs. I will quantize the model using the static method.

**Comment by cainiaoshidai** [comment]
> I was able to reproduce the issue. Interestingly, the issue doesn't reproduce in CPU and WASM. Likely, there is something wrong on the GPU provider side. I suggest you open an issue in the ONNX runtime repo.

Thanks,  I will open an issue in the ONNX runtime repo.

**Comment by earsonlau** [comment]
> The [notebook](https://github.com/visheratin/segment-anything/blob/main/notebooks/full_onnx_model_example.ipynb) from the PR has the complete code for using both the encoder and decoder for predictions. Let me know if something else needs to be added.

Hi visheratin, you've done a nice work! From the notebook you provided, we need to input a certain point in the onnx model to produce a mask. Can you provide some code that can we display all masks like in this photo?
image

**Comment by vietanhdev** [comment]
@visheratin Thank you very much for your great efforts on ONNX models.
I have used your converted ONNX models (I supposed they are located at [https://huggingface.co/visheratin](https://huggingface.co/visheratin)) for [AnyLabeling](https://github.com/vietanhdev/anylabeling) - an auto labeling tool based on labelme and Segment Anything. Some modifications I've made:
+ Rewritten preprocessing with `numpy` to avoid installing other packages.
+ Worked on padding to prevent shifted results on static shape ONNX models.
+ Some of the models are multi-mask, so I pick the first mask only for the labeling tool.
The code for Segment Anything is located [here](https://github.com/vietanhdev/anylabeling/blob/master/anylabeling/services/auto_labeling/segment_anything.py).

**Comment by zgplvyou** [comment]
@visheratin Hey, thank u for the encoder onnx model. I found the encoder onnx model and the decoder model are separated. That means when i process an image, firstly, i need to load the encoder onnx mdoel and get the image embedding, then, load the decoder onnx model and use the image embeeding as input. so why not directly export one onnx model and take the whole input?

**Comment by zgplvyou** [comment]
> @zgplvyou Because you generate image embedding using a heavy encoder once, and then you can prompt it with points and boxes any number of times using a lightweight decoder. As far as I know, ONNX doesn't support optional inputs. Because of that, if you export the model with an encoder and decoder combined, you will have to run the encoder on every prompt, which is a huge overhead.

It seems reasonable to export different onnx models. And the prompt encoder onnx model contains all prompts of points, boxes and  masks. It means that even if you need only one point prompt as input, you have to provide the dummy box and mask prompt inputs, which different from the dynamic pytorch model.

**Comment by zgplvyou** [comment]
I try to load the whole onnx model of encoder and decoder and I failed to infer on onnxruntime framework. however, I can successfully run the single encoder onnx model or decoder onnx model  on onnxruntime. I don`t konw if you have the same change. I just change the forward function in SamOnnxModel:  image_embeddings = self.image_encoder(x).

**Comment by OroChippw** [comment]
> I didn't try to export and run the full model because of the reasons I described above.

Thank you so much for releasing the code of the export encoder to onnx! Can you provide any scripts to run the export_onnx_model.py ?when i try to convert encoder to onnx without param --encoder-data-file my vscode program crash😥？I wonder what should i provide to the --encoder-data-file param ,Thank you~

**Comment by machine52vision** [comment]
> The [notebook](https://github.com/visheratin/segment-anything/blob/main/notebooks/full_onnx_model_example.ipynb) from the PR has the complete code for using both the encoder and decoder for predictions. Let me know if something else needs to be added.

how export  sam encoder model to onnx? can you provide code

**Comment by vietanhdev** [comment]
@machine52vision  Checkout this package for converting + inference code for both encoder and decoder: https://github.com/vietanhdev/samexporter.

**Comment by machine52vision** [comment]
thank you very much



---- Replied Message ----
| From | Viet-Anh, ***@***.***> |
| Date | 05/11/2023 20:10 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [facebookresearch/segment-anything] Added encoder export to ONNX (PR #29) |

@machine52vision Checkout this package for converting + inference code for both encoder and decoder: https://github.com/vietanhdev/samexporter.

**Comment by mlruns** [comment]
> I try to load the whole onnx model of encoder and decoder and I failed to infer on onnxruntime framework. however, I can successfully run the single encoder onnx model or decoder onnx model on onnxruntime. I don`t konw if you have the same change. I just change the forward function in SamOnnxModel: image_embeddings = self.image_encoder(x).

I tried to infer on onnxruntime framework but it failed for me. could you share how you did infer in onnxruntime framework.

**Comment by mlruns** [comment]
> > > I try to load the whole onnx model of encoder and decoder and I failed to infer on onnxruntime framework. however, I can successfully run the single encoder onnx model or decoder onnx model on onnxruntime. I don`t konw if you have the same change. I just change the forward function in SamOnnxModel: image_embeddings = self.image_encoder(x).
> > 
> > 
> > I tried to infer on onnxruntime framework but it failed for me. could you share how did you infer in onnxruntime framework?
> 
> Hope my code can help you python + onnxruntime with encoder : https://github.com/OroChippw/segment-anything/blob/fangzj/run_SegAnything_onnx_with_encoder.py python + onnxruntime without encoder : https://github.com/OroChippw/segment-anything/blob/fangzj/run_SegAnything_onnx.py C++ + onnxruntime : https://github.com/OroChippw/SegmentAnything-OnnxRunner/blob/master/SAMOnnxRunner/SAMOnnxRunner.cpp


thank you for sharing your amazing work. I have noticed that your exported encoder is of size 342 MB, However when i have converted the encoder using samexporter repo I got onnx of size 1.67 MB.  I dont know what I am missing here, could you clarify please?

**Comment by OroChippw** [comment]
> > > > I try to load the whole onnx model of encoder and decoder and I failed to infer on onnxruntime framework. however, I can successfully run the single encoder onnx model or decoder onnx model on onnxruntime. I don`t konw if you have the same change. I just change the forward function in SamOnnxModel: image_embeddings = self.image_encoder(x).
> > > 
> > > 
> > > I tried to infer on onnxruntime framework but it failed for me. could you share how did you infer in onnxruntime framework?
> > 
> > 
> > Hope my code can help you python + onnxruntime with encoder : https://github.com/OroChippw/segment-anything/blob/fangzj/run_SegAnything_onnx_with_encoder.py python + onnxruntime without encoder : https://github.com/OroChippw/segment-anything/blob/fangzj/run_SegAnything_onnx.py C++ + onnxruntime : https://github.com/OroChippw/SegmentAnything-OnnxRunner/blob/master/SAMOnnxRunner/SAMOnnxRunner.cpp
> 
> thank you for sharing your amazing work. I have noticed that your exported encoder is of size 342 MB, However when i have converted the encoder using samexporter repo I got onnx of size 1.67 MB. I dont know what I am missing here, could you clarify please?

I guess you are not converting the same size model, vit-b will convert a 342MB onnx model for the encoder, and vit-h will convert a 1.25MB onnx model and a 2.37GB binary file

**Comment by mlruns** [comment]
> > > > > I try to load the whole onnx model of encoder and decoder and I failed to infer on onnxruntime framework. however, I can successfully run the single encoder onnx model or decoder onnx model on onnxruntime. I don`t konw if you have the same change. I just change the forward function in SamOnnxModel: image_embeddings = self.image_encoder(x).
> > > > 
> > > > 
> > > > I tried to infer on onnxruntime framework but it failed for me. could you share how did you infer in onnxruntime framework?
> > > 
> > > 
> > > Hope my code can help you python + onnxruntime with encoder : https://github.com/OroChippw/segment-anything/blob/fangzj/run_SegAnything_onnx_with_encoder.py python + onnxruntime without encoder : https://github.com/OroChippw/segment-anything/blob/fangzj/run_SegAnything_onnx.py C++ + onnxruntime : https://github.com/OroChippw/SegmentAnything-OnnxRunner/blob/master/SAMOnnxRunner/SAMOnnxRunner.cpp
> > 
> > 
> > thank you for sharing your amazing work. I have noticed that your exported encoder is of size 342 MB, However when i have converted the encoder using samexporter repo I got onnx of size 1.67 MB. I dont know what I am missing here, could you clarify please?
> 
> I guess you are not converting the same size model, vit-b will convert a 342MB onnx model for the encoder, and vit-h will convert a 1.25MB onnx model and a 2.37GB binary file

yes I am converting vit-h model, Thanks for clarification. I hope it works fine with c++.

**Comment by mlruns** [comment]
> > > > > > I try to load the whole onnx model of encoder and decoder and I failed to infer on onnxruntime framework. however, I can successfully run the single encoder onnx model or decoder onnx model on onnxruntime. I don`t konw if you have the same change. I just change the forward function in SamOnnxModel: image_embeddings = self.image_encoder(x).
> > > > > 
> > > > > 
> > > > > I tried to infer on onnxruntime framework but it failed for me. could you share how did you infer in onnxruntime framework?
> > > > 
> > > > 
> > > > Hope my code can help you python + onnxruntime with encoder : https://github.com/OroChippw/segment-anything/blob/fangzj/run_SegAnything_onnx_with_encoder.py python + onnxruntime without encoder : https://github.com/OroChippw/segment-anything/blob/fangzj/run_SegAnything_onnx.py C++ + onnxruntime : https://github.com/OroChippw/SegmentAnything-OnnxRunner/blob/master/SAMOnnxRunner/SAMOnnxRunner.cpp
> > > 
> > > 
> > > thank you for sharing your amazing work. I have noticed that your exported encoder is of size 342 MB, However when i have converted the encoder using samexporter repo I got onnx of size 1.67 MB. I dont know what I am missing here, could you clarify please?
> > 
> > 
> > I guess you are not converting the same size model, vit-b will convert a 342MB onnx model for the encoder, and vit-h will convert a 1.25MB onnx model and a 2.37GB binary file
> 
> yes I am converting vit-h model, Thanks for clarification. I hope it works fine with c++.

When I am running in c++, I am getting error could not find model.bin file while running encoder onnx file. Have you faced the same issue ?

**Comment by mj-Liusirs** [comment]
> > 由于 ONNX 模型是动态量化的，因此会给推理增加一些开销。您可以在此处阅读更多内容 [here](https://onnxruntime.ai/docs/performance/model-optimizations/quantization.html#dynamic-quantization)。考虑到用例的多样性，我认为静态量化在SAM的情况下效果不佳。如果您的用例较窄，则可以尝试使用目标数据作为校准数据集来静态量化模型 [calibration dataset](https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/python/tools/quantization/calibrate.py)。
> 
> 谢谢。动态量化将 GPU 上的推理时间增加了 80%。我将使用静态方法量化模型。

**Comment by mj-Liusirs** [comment]
> I will quantize the model using the static method.



> > Since ONNX models are dynamically quantized, it adds some overheads to the inference. You can read more on that [here](https://onnxruntime.ai/docs/performance/model-optimizations/quantization.html#dynamic-quantization). Considering the diversity of use cases, I think that static quantization won't work well in the case of SAM. If you have a narrow use case, you can try to statically quantize the model using your target data as a [calibration dataset](https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/python/tools/quantization/calibrate.py).
> 
> Thanks. The dynamic quantization increases inference time by 80% on GPUs. I will quantize the model using the static method.

May I ask if you have successfully obtained the onnx model after static quantization？

**Comment by andrea-cimatoribus-pix4d** [comment]
I cross-list this issue https://github.com/microsoft/onnxruntime/issues/20983 in case others are having speed issues using SAM with onnxruntime on Windows. I am struggling to find any relevant information on this.

**Pull request closed without merging**
